version: '1'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10
    restart: always
    ports:
      - 53306:3306
    volumes:
      - /mnt/c/project/docker_volumes/mariadb/conf.d:/etc/mysql/conf.d
      - /mnt/c/project/docker_volumes/mariadb/data:/var/lib/mysql
      - /mnt/c/project/docker_volumes/mariadb/log:/var/log/mysql
      - /mnt/c/project/docker_volumes/mariadb/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MARIADB_DATABASE: board_study
      MARIADB_USER: kosa
      MARIADB_PASSWORD: 1004kosa
      MARIADB_ROOT_PASSWORD: 1004kosa
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis
  was1:
    image: cachedemo/cache:0.1
    environment:
      USE_PORT: 8090
    ports:
      - 8090:8090
    container_name: was1
    depends_on:
      - redis
      - mariadb
  was2:
    image: cachedemo/cache:0.1
    environment:
      USE_PORT: 9090
    ports:
      - 9090:8090
    container_name: was2
    depends_on:
      - redis
      - mariadb
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /mnt/c/project/docker_volumes/nginx/nginx.conf:/etc/nginx/nginx.conf 
      - /mnt/c/project/docker_volumes/nginx/log:/var/log/nginx 
      - /mnt/c/project/docker_volumes/nginx/html:/usr/share/nginx/html 
    container_name: nginx
    depends_on:
      - was1
      - was2
